name: ci

on:
  schedule:
    - cron: '0 0 * * *' # every 4 hours
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

env:
  DOCKER_IMAGE: localhost:5000/name/app

jobs:
  multi-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        uses: ./
        with:
          images: |
            ${{ env.DOCKER_IMAGE }}
            ghcr.io/name/app

  tag-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        uses: ./
        with:
          images: |
            ${{ env.DOCKER_IMAGE }}
            ghcr.io/name/app
          tag-schedule: scheduled

  tag-semver:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tag-latest:
          - 'true'
          - 'false'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        uses: ./
        with:
          images: |
            ${{ env.DOCKER_IMAGE }}
            ghcr.io/name/app
          tag-semver: |
            {{raw}}
            {{version}}
            {{major}}.{{minor}}.{{patch}}
          tag-latest: ${{ matrix.tag-latest }}

  label-custom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        uses: ./
        with:
          images: |
            ${{ env.DOCKER_IMAGE }}
            ghcr.io/name/app
          label-custom: |
            maintainer=CrazyMax
            org.opencontainers.image.title=MyCustomTitle
            org.opencontainers.image.description=Another description
            org.opencontainers.image.vendor=MyCompany
